name: Trigger https://xuekaiyuan.pages.dev deploy hook

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Trigger job
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: POST https://xuekaiyuan.pages.dev deploy hook
        run: |
          curl \
            -X POST \
            "${{ secrets.TRIGGER_XUEKAIYUAN_PAGES_DEV }}"
